version: "3"

volumes:
  dbdata:
  wordpress:

networks:
  docker-app:
    driver: bridge

services:
  database:
    container_name: mysql_database
    restart: always
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE: mysql-db
      - MYSQL_USER: username
      - MYSQL_PASSWORD: password
      - MYSQL_ROOT_PASSWORD: password1
    networks:
      - docker-app

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - PMA_HOST: database
      - MYSQL_USER: username
      - MYSQL_PASSWORD: password
      - MYSQL_ROOT_PASSWORD: password1
    networks:
      - docker-app

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST: database
      - WORDPRESS_DB_USER: phpmyadmin
      - WORDPRESS_DB_PASSWORD: phpmyadmin
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-app

   nginx:
     depends_on:
       - wordpress
     image: nginx:latest
     container_name: nginx
     restart: always
     volumes:
       - wordpress:/var/www/html
       - ./nginx-conf:/etc/nginx/conf.d
     networks:
      - docker-app
       
