version: '3'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lemp-app
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db:3306
      MYSQL_ROOT_PASSWORD: password1
    networks:
      - lemp-app
    links:
      - mysql-db

  wordpress:
    depends_on:
      - mysql-db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - wordpress:/var/www/html
    networks:
      - lemp-app
    links:
      - mysql-db      

  nginx:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - lemp-app


volumes:
  wordpress:
  dbdata:
  
networks:
  lemp-app:
    driver: bridge
